### ISSUE TITLE
while using wildcard in order to fetch repos dynimcally, other publich repositories are being fetched

### ISSUE THREAD

**Issue by TalShlomiNielsen** [mvisonneau/gitlab-ci-pipelines-exporter#176]
hey @mvisonneau, I'm using Wildcard in order to fetch dynamically repositories but still other not relevant repos are being fetched. 

my config: 
`
  wildcards:
    - owner: { name: tal.shlomi/test, kind: group, include_subgroups: true }
    - owner: { name: ron.merkin/test kind: group, include_subgroups: true }
    - pull:
        refs:
          from:
            merge_requests:
              enabled: true
`

still repositories which are not in the group are being fetched like :  group1910/proj19 or gefugn37we/home

another Question is regarding the the way I use the pull is it the right convention?

Thank you very

**Comment by mvisonneau** [comment]
Indeed, I recently stumbled upon this scenario. I believe this is due to a behavorial change on the GitLab API which now returns all the project on which the `group` or `user` as access upon even though it isn't the actual owner of it. I'll put some thoughts on how to revert this back to the intended behaviour.

**Comment by mvisonneau** [comment]
I believe that by defaulting the `search` parameter to the actual owner could be a way 🤔

**Comment by mvisonneau** [comment]
I found the culprit and the fix is now part of [v0.4.3](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/v0.4.3)
