### ISSUE TITLE
Monitor shows ascii code instead of coloured display

### ISSUE THREAD

**Issue by gallipi** [mvisonneau/gitlab-ci-pipelines-exporter#402]
![1](https://user-images.githubusercontent.com/79204852/151928284-e08b1984-64cb-4a98-aa14-63b7c7e7a64b.jpg)

Hi mvisonneau,

I'm testing the monitor functionality and although I'm getting the information It is not displayed in a pretty format (colours, progress bars,tabs,...) as you can see in the attached image. I guess I'm missing some library, could you please help me?

OS: RHEL 8.4
GCPE_INTERNAL_MONITORING_LISTENER_ADDRESS='unix://gcpe-monitor.sock'

Thanks in advance

**Comment by mvisonneau** [comment]
interesting, as we are leveraging the following library: https://github.com/charmbracelet/lipgloss I would suggest you to dig into their issue tracker to see if you find something similar. I have updated the libraries recently so if you are using the `latest` tag of the released container image and they have provided some enhancements since, it might sort your issue out 🤷

**Comment by gallipi** [comment]
Solved applying these configurations

RedHat
`export TERM=xterm-256color`
`export COLORTERM=true`

PuTTY
`Settings -> Window -> Translation -> UTF-8`

**Comment by mvisonneau** [comment]
thanks for the info!
