### ISSUE TITLE
Add status label to time fields to properly represent time for appropriate run success vs failed or canceled, etc.

### ISSUE THREAD

**Issue by virtuman** [mvisonneau/gitlab-ci-pipelines-exporter#43]
Currently it doesn't have a label for status of the pipeline, and it results in skewed reports. We have failed pipelines, and no way to filter them out from the reports. 

Would be great to add status label to the time-specific metrics, then we could display HEALTHY & RUNNING based on true successful runs only.

Thank you for your consideration.

**Comment by mvisonneau** [comment]
👋 Hey @virtuman thanks for raising the issue. I am not sure to understand what you are looking for though? 🤔 at first sight having this kind of label does not seem to be aligned with the prometheus/open metrics philosophy?

**Comment by lovelaced** [comment]
Maybe I can clarify because this sounds like an issue I'm also having. I would like to definitively discern between the status of jobs. Some jobs are still technically "running" but are actually cancelled, or pending. They should not be labeled running indefinitely, they should pick up cancelled/failed labels correctly and ideally establish if there is a paused or pending job in the pipeline to trigger some sort of label in the pipeline like "has_pending_jobs" so they can be filtered out of the running job status, for instance.

**Comment by spacez320** [comment]
@virtuman If you're using Prometheus, this PromQL query would get you Pipeline runtimes while excluding those that are not succeeded.

```
gitlab_ci_pipeline_last_run_duration_seconds and on (project) gitlab_ci_pipeline_last_run_status{status="success"} == 1
```

**Comment by mvisonneau** [comment]
I believe this was also an effect of the jobs refresh errors highlighted in #119 and #150. There was also some errors in the dashboard which I fixed recently. I assume this will be sorted with the [0.4.0](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/0.4.0) release. Feel free to reopen if not!
