### ISSUE TITLE
Adapting this component to Azure Pipelines

### ISSUE THREAD

**Issue by zied-chekir** [mvisonneau/gitlab-ci-pipelines-exporter#858]
I wanted to post this question on Slack or Discord but couldn't find the right link, so I'm posting it here and hope it's okay.
We are currently using Azure DevOps and want to monitor our CI pipelines. Is it possible to adapt this component for Azure Pipelines by modifying some API endpoints ( since azure provides REST API for pipelines [here](https://learn.microsoft.com/en-us/rest/api/azure/devops/pipelines/?view=azure-devops-rest-7.0) ), or is that not feasible?

**Comment by mvisonneau** [comment]
👋 hey @zied-chekir, thanks for your question. I do not believe the scope of this project will be extended beyond GitLab CI. Feel free to inspire yourself from it if you are interested into supporting Azure CI. Some vendors such as Datadog already [offer similar capabilities](https://docs.datadoghq.com/continuous_integration/pipelines/azure/) otherwise.
