### ISSUE TITLE
Historical data?

### ISSUE THREAD

**Issue by lovelaced** [mvisonneau/gitlab-ci-pipelines-exporter#94]
Hi there and thanks so much for this, very useful.

I was wondering if there's a way to only retrieve refs starting from a certain period of time rather than ALL time. We are working with a TON of refs from years ago and it creates a lot of prometheus data we really don't need. Something like "only start getting refs from new jobs" or something like that. Am I overlooking a configuration option or is this not possible at this time?

Thanks!

**Comment by mvisonneau** [comment]
👋 thank you for the kind feedback @lovelaced 

Currently you have 2 options:

- If the **refs** have been deleted already you can use the I believe you can use the `on_init_fetch_refs_from_pipelines` and `on_init_fetch_refs_from_pipelines_depth_limit` parameters.
- Otherwise, you will unfortunately have to tweak the `default_refs` and/or `refs` parameters to filter out only the ones that you need.

It could be an idea to have an additionnal parameter to fetch the `n recently active` or the `newer than x amount of time` ones I guess 🤔

**Comment by lovelaced** [comment]
I think `newer than x amount of time` would work well for people with existing setups that don't want to import pipeline data from the entirety of history. Prometheus is likely only going to be looking at some smaller number of weeks/months, so an option to filter that out would be great. 

Meanwhile I'll give the `default.refs_regexp` a shot, thanks for the help.

**Comment by mvisonneau** [comment]
hey @lovelaced, the [0.4.0](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/0.4.0) release should help you further with this issue. It is now possible to control more precisely the pull configuration to avoid having to pull all the resources on the start. You can also now use redis to cache the data as well as leveraging gitlab webhooks to reduce the amount of requests being made even further whilst keeping consistency/integrity across the board.

I will therefore close this issue but feel free to reopen if necessary!
